name: Demos

on: [push, pull_request]

jobs:
  validate-configs:
    name: Validate configurations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: json-yaml-validate
        uses: GrantBirki/json-yaml-validate@v3.3.0
        with:
          json_schema: ./schemas/robot.schema.json
          yaml_as_json: true
          files: |
            demos/config_solo12.yaml
            demos/config_testbench.yaml
