name: CI - Nix

on: [push, pull_request]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: gepetto
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix flake check -L
      - name: Check if there are changes
        uses: NathanielHill/fail-if-changes@v1.1.1
